version: 2

# *****************
# Jobs
# *****************

jobs:

  # website
  website:
    docker: 
      - image: coxy1989/pandoc-aws
    steps:
      - checkout
      # - run: 
      #     name: Convert markdown to html
      #     command: (bash _convert_markdown_to_html.sh)
      - run:  
          name: Upload output to s3 host
          command: (aws s3 cp output --exclude * --include content s3://host-website-live --recursive;
                    aws s3 cp output --exclude * --include vendor s3://host-website-live --recursive;
                    aws s3 cp output --exclude * --include index.html s3://host-website-live --recursive;)


# *****************
# Workflows
# *****************

workflows:
  version: 2
  master:
    jobs:

      # website
      - website:
          filters:
            branches:
              only:
                - master

