version: 2

# *****************
# Jobs
# *****************

jobs:

  # website
  website:
    docker: 
      - image: coxy1989/pandoc-aws
    steps:
      - checkout
      - run: 
          name: Go to content dir
          command: (cd content)
      # - run: 
      #     name: Convert markdown to html
      #     command: (bash _convert_markdown_to_html.sh)
      - run:  
          name: Upload to s3 host
          command: (aws s3 cp content s3://host-website-live --exclude "*" --include "css/*" --recursive ;
                    aws s3 cp content s3://host-website-live --exclude "*" --include "assets/*"  --recursive 
                    aws s3 cp content/html s3://host-website-live --exclude "*" --include "*html"  --recursive)


# *****************
# Workflows
# *****************

workflows:
  version: 2
  master:
    jobs:

      # website
      - website:
          filters:
            branches:
              only:
                - master

